# Generated by Django 4.2.7 on 2023-11-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammingLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Programming language"
                    ),
                ),
                (
                    "slug",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "City name",
                "verbose_name_plural": "Programming languages",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City name", "verbose_name_plural": "City names"},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="City name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
