# Generated by Django 4.2.7 on 2023-12-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0002_programminglanguage_alter_city_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Title of vacancy"),
                ),
                (
                    "company_name",
                    models.CharField(max_length=250, verbose_name="Company name"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description of vacancy"),
                ),
                ("timestamp", models.DateField(auto_now_add=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraping.city",
                        verbose_name="City",
                    ),
                ),
                (
                    "programming_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scraping.programminglanguage",
                        verbose_name="Programming Language",
                    ),
                ),
            ],
            options={"verbose_name": "Vacancy", "verbose_name_plural": "Vacancy",},
        ),
    ]
